# Generated by Django 3.2.6 on 2021-09-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractName', models.CharField(max_length=100)),
                ('ContractDescription', models.TextField(default='Enter Contract Description', max_length=4000)),
                ('ContractTasks', models.TextField(default='Enter Contract Tasks', max_length=40000)),
                ('StartDate', models.CharField(default='Enter Start Date DD/MM/YY', max_length=8)),
                ('EndDate', models.CharField(default='Enter End Date DD/MM/YY', max_length=8)),
            ],
        ),
    ]
