# Generated by Django 3.2.6 on 2021-09-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2project', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='ContractDescription',
            field=models.TextField(default='Enter Contract Description', max_length=40000),
        ),
    ]
