# Generated by Django 3.2.6 on 2021-09-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2project', '0004_alter_contract_contractdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='EndDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='StartDate',
            field=models.DateField(),
        ),
    ]
