# Generated by Django 3.2.6 on 2021-09-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2project', '0005_auto_20210907_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='EndDate',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='StartDate',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
