# Generated by Django 3.2.6 on 2021-09-07 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b2project', '0007_auto_20210907_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b2project.userprofile'),
        ),
    ]
