# Generated by Django 3.2.6 on 2021-09-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2project', '0009_remove_contract_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='ContractDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='EndDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='ContractName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='StartDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='ContractTasks',
            new_name='tasks',
        ),
    ]
