# Generated by Django 3.2.6 on 2021-09-07 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2project', '0010_auto_20210907_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='description',
            new_name='ContractDescription',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='name',
            new_name='ContractName',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='tasks',
            new_name='ContractTasks',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='end_date',
            new_name='EndDate',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='start_date',
            new_name='StartDate',
        ),
    ]
