# Generated by Django 3.2.6 on 2021-09-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2project', '0012_auto_20210907_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='ContractDescription',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ContractTasks',
            field=models.TextField(max_length=3000),
        ),
    ]
