# Generated by Django 3.2.6 on 2021-09-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2project', '0015_auto_20210909_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='Payment',
            field=models.TextField(default='', max_length=40000),
        ),
    ]
