# Generated by Django 3.2.6 on 2021-09-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2project', '0018_auto_20210910_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarystatement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
