# Generated by Django 3.2.6 on 2021-09-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2project', '0019_alter_salarystatement_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalaryStatement',
        ),
        migrations.AddField(
            model_name='contract',
            name='SalaryStatement',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
